### ISSUE TITLE
Regression in 0.29.0: NoMethodError: undefined method `path' for nil:NilClass in haml_lint/rake_task.rb:50:in `config'

### ISSUE THREAD

**Issue by jaredbeck** [sds/haml-lint#300]
`bin/rake`works in 0.28.0, raises NoMethodError in 0.29.0

### Definition of rake task

```ruby
# lib/tasks/haml_lint.rb
if defined?(::HamlLint)
  require 'haml_lint/rake_task'
  HamlLint::RakeTask.new
end

# Rakefile
task default: [] # in case it hasn't been set
::Rake::Task[:default].clear
task :default do
  # ... a few tasks
  ::Rake::Task['haml_lint'].invoke
  # ... a few more tasks
```

### Stack Trace

```
bin/rake --trace
** Invoke default (first_time)
** Execute default
** Invoke rubocop (first_time)
** Execute rubocop
...
** Invoke haml_lint (first_time)
** Execute haml_lint
rake aborted!
NoMethodError: undefined method `path' for nil:NilClass
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/haml_lint-0.29.0/lib/haml_lint/rake_task.rb:50:in `config'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/haml_lint-0.29.0/lib/haml_lint/rake_task.rb:143:in `parse_args'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/haml_lint-0.29.0/lib/haml_lint/rake_task.rb:106:in `run_cli'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/haml_lint-0.29.0/lib/haml_lint/rake_task.rb:98:in `block in define'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/jared/git/REDACTED/Rakefile:27:in `block in <top (required)>'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/jared/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
bin/rake:6:in `<main>'
Tasks: TOP => haml_lint
```

### Disclaimer

I've never understood rake well, so there's a non-zero chance I'm doing something wrong in my rake file. Maybe the fact that it worked in 0.28 was just a lucky accident.

Please let me know how I can help further with this. Thanks! Enjoying using `haml_lint` so far!

**Comment by sds** [comment]
Thanks for the report, @jaredbeck. Released a fix in [0.30.0](https://github.com/sds/haml-lint/releases/tag/v0.30.0)

**Comment by jaredbeck** [comment]
> Released a fix in 0.30.0

Thanks!

> I tried coming up with a test case for this but .. You can only instantiate one instance of a given Rake task (based on my understanding) and there isn't a convenient way to swap this out ..

I've never understood rake 😅 To replace a task in our Rakefile, we use:

```
task x: [] # in case it hasn't been set
::Rake::Task[:x].clear
task :x do ...
```

Does that help?
