### ISSUE TITLE
0.63.0 appears to break rubocop run for text_field_tag's when first param is a variable (not a string or symbol)

### ISSUE THREAD

**Issue by maddieholtzer** [sds/haml-lint#577]
I still have more investigation to do here but 0.63.0 appears to no longer work when the first param of a [text_field_tag](https://apidock.com/rails/v5.2.3/ActionView/Helpers/FormTagHelper/text_field_tag) is a variable. This appears to be very specific to text fields, as it works for other tags such as a text_area_tag.

```
# Works in 0.62.0 but fails in 0.63.0
= text_field_tag(input_name)

# Works in 0.63.0 still
= text_field_tag('input_name')
= text_field_tag(:input_name)
= text_area_tag(input_name)
```

Stacktrace:
```
app/views/components/_email_form.html.haml:0 [E] RuboCop: Couldn't process the file for linting. HamlLint::Exceptions::ConfigurationError: RuboCop raised RuboCop::ErrorWithAnalyzedFileLocation. Here is its output to check the stack trace or see if there was a misconfiguration:
cause: #<NoMethodError: undefined method 'value' for an instance of RuboCop::AST::SendNode>
["/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/commissioner.rb:176:in 'RuboCop::Cop::Commissioner#with_cop_error_handling'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/commissioner.rb:106:in 'block in RuboCop::Cop::Commissioner#trigger_responding_cops'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/commissioner.rb:105:in 'Array#each'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/commissioner.rb:105:in 'RuboCop::Cop::Commissioner#trigger_responding_cops'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/commissioner.rb:69:in 'RuboCop::Cop::Commissioner#on_send'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:169:in 'block in RuboCop::AST::Traversal#on_send'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:166:in 'Array#each'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:166:in 'Enumerable#each_with_index'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:166:in 'RuboCop::AST::Traversal#on_send'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/commissioner.rb:71:in 'RuboCop::Cop::Commissioner#on_send'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:146:in 'block in RuboCop::AST::Traversal#on_dstr'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:146:in 'Array#each'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:146:in 'RuboCop::AST::Traversal#on_dstr'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/commissioner.rb:71:in 'RuboCop::Cop::Commissioner#on_begin'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:149:in 'block in RuboCop::AST::Traversal#on_case'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:149:in 'Array#each'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:149:in 'RuboCop::AST::Traversal#on_case'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/commissioner.rb:71:in 'RuboCop::Cop::Commissioner#on_ensure'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:146:in 'block in RuboCop::AST::Traversal#on_dstr'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:146:in 'Array#each'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:146:in 'RuboCop::AST::Traversal#on_dstr'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/commissioner.rb:71:in 'RuboCop::Cop::Commissioner#on_kwbegin'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:146:in 'block in RuboCop::AST::Traversal#on_dstr'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:146:in 'Array#each'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:146:in 'RuboCop::AST::Traversal#on_dstr'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/commissioner.rb:71:in 'RuboCop::Cop::Commissioner#on_begin'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.45.1/lib/rubocop/ast/traversal.rb:20:in 'RuboCop::AST::Traversal#walk'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/commissioner.rb:87:in 'RuboCop::Cop::Commissioner#investigate'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/team.rb:174:in 'RuboCop::Cop::Team#investigate_partial'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/cop/team.rb:108:in 'RuboCop::Cop::Team#investigate'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:348:in 'block in RuboCop::Runner#inspect_file'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:347:in 'Array#each'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:347:in 'Enumerable#flat_map'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:347:in 'RuboCop::Runner#inspect_file'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:290:in 'block in RuboCop::Runner#do_inspection_loop'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:324:in 'block in RuboCop::Runner#iterate_until_no_changes'", "<internal:kernel>:168:in 'Kernel#loop'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:317:in 'RuboCop::Runner#iterate_until_no_changes'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:286:in 'RuboCop::Runner#do_inspection_loop'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:167:in 'block in RuboCop::Runner#file_offenses'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:192:in 'RuboCop::Runner#file_offense_cache'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:166:in 'RuboCop::Runner#file_offenses'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:154:in 'RuboCop::Runner#process_file'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:135:in 'block in RuboCop::Runner#each_inspected_file'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:134:in 'Array#each'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:134:in 'Enumerable#reduce'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:134:in 'RuboCop::Runner#each_inspected_file'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:120:in 'RuboCop::Runner#inspect_files'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rubocop-1.77.0/lib/rubocop/runner.rb:73:in 'RuboCop::Runner#run'", "/haml-lint/lib/haml_lint/linter/rubocop.rb:27:in 'HamlLint::Linter::RuboCop::Runner#run'", "/haml-lint/lib/haml_lint/linter/rubocop.rb:230:in 'HamlLint::Linter::RuboCop#run_rubocop'", "/haml-lint/lib/haml_lint/linter/rubocop.rb:216:in 'HamlLint::Linter::RuboCop#process_ruby_source'", "/haml-lint/lib/haml_lint/linter/rubocop.rb:98:in 'HamlLint::Linter::RuboCop#visit_root'", "/haml-lint/lib/haml_lint/haml_visitor.rb:42:in 'HamlLint::HamlVisitor#safe_send'", "/haml-lint/lib/haml_lint/haml_visitor.rb:21:in 'HamlLint::HamlVisitor#visit'", "/haml-lint/lib/haml_lint/linter.rb:66:in 'HamlLint::Linter#run_or_raise'", "/haml-lint/lib/haml_lint/linter.rb:28:in 'HamlLint::Linter#run'", "/haml-lint/lib/haml_lint/runner.rb:107:in 'block in HamlLint::Runner#collect_lints'", "/haml-lint/lib/haml_lint/runner.rb:106:in 'Array#map'", "/haml-lint/lib/haml_lint/runner.rb:106:in 'HamlLint::Runner#collect_lints'", "/haml-lint/lib/haml_lint/runner.rb:193:in 'block in HamlLint::Runner#warm_cache'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:650:in 'Parallel.call_with_index'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:620:in 'Parallel.process_incoming_jobs'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:600:in 'block in Parallel.worker'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:591:in 'Process.fork'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:591:in 'Parallel.worker'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:582:in 'block in Parallel.create_workers'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:581:in 'Array#each'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:581:in 'Enumerable#each_with_index'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:581:in 'Parallel.create_workers'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:520:in 'Parallel.work_in_processes'", "/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parallel-1.27.0/lib/parallel.rb:291:in 'Parallel.map'", "/haml-lint/lib/haml_lint/runner.rb:192:in 'HamlLint::Runner#warm_cache'", "/haml-lint/lib/haml_lint/runner.rb:183:in 'HamlLint::Runner#report'", "/haml-lint/lib/haml_lint/runner.rb:33:in 'HamlLint::Runner#run'", "/haml-lint/lib/haml_lint/cli.rb:114:in 'HamlLint::CLI#scan_for_lints'", "/haml-lint/lib/haml_lint/cli.rb:58:in 'HamlLint::CLI#act_on_options'", "/haml-lint/lib/haml_lint/cli.rb:25:in 'HamlLint::CLI#run'", "/haml-lint/bin/haml-lint:7:in '<top (required)>'", "/ruby/3.4.4/bin/haml-lint:25:in 'Kernel#load'", "/ruby/3.4.4/bin/haml-lint:25:in '<main>'", "/ruby/3.4.4/bin/ruby_executable_hooks:22:in 'Kernel#eval'", "/ruby/3.4.4/bin/ruby_executable_hooks:22:in '<main>'"]
```
